  0%|          | 0/4 [00:00<?, ?it/s] 25%|██▌       | 1/4 [00:00<00:00,  3.23it/s] 50%|█████     | 2/4 [00:00<00:00,  3.53it/s] 75%|███████▌  | 3/4 [00:00<00:00,  3.61it/s]100%|██████████| 4/4 [00:01<00:00,  3.69it/s]100%|██████████| 4/4 [00:01<00:00,  3.61it/s]
  0%|          | 0/201 [00:00<?, ?it/s]  0%|          | 0/201 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 108, in <module>
    n_smooth=config.n_smooth, lambd=config.lambd)
  File "/opt/miniconda3/envs/pialnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pialnn/model/pialnn_mod.py", line 121, in forward
    x = self.block1(v, f, volume)
  File "/opt/miniconda3/envs/pialnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pialnn/model/pialnn_mod.py", line 37, in forward
    normal = compute_normal(v, f)    # compute normal
  File "/pialnn/utils.py", line 49, in compute_normal
    faces=list(f)).verts_normals_list()[0]
  File "/opt/miniconda3/envs/pialnn/lib/python3.7/site-packages/pytorch3d/structures/meshes.py", line 356, in __init__
    "All Verts and Faces tensors should be on same device."
ValueError: All Verts and Faces tensors should be on same device.
